version: "3"
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
  nodejs:
    build:
      context: .
      dockerfile: docker/Dockerfile.nodejs
    volumes:
      - .:/var/www

